export const NavigationType = {
  HOME_SCREEN: 'HOME_SCREEN',
  CHARACTER_DETAIL: 'CHARACTER_DETAIL',
  FAVOURITE_SCREEN: 'FAVOURITE_SCREEN',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
};

export const actionTypes = {
  GET_CHARACTERS: 'GET_CHARACTERS',
  ADD_TO_FAVOURITE: 'ADD_TO_FAVOURITE',
  REMOVE_FAVOURITE: 'REMOVE_FAVOURITE',
  SEARCH_CHARACTER: 'SEARCH_CHARACTER',
  REMOVE_SEARCH_CHARACTER: 'REMOVE_SEARCH_CHARACTER',
};

export const colors = {
  white: '#fff',
  black: '#000',
  green: '#18CA75',
  color3d3d3d: '#3d3d3d',
  pink: '#CA184E',
};
